name: listen-mc-decompile
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean shadowJar -s

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/gitmc.jar

  listen:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out Version Branch
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DESTINATION }}
          ref: version
          ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          path: version

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: build/libs

      - name: Check Minecraft version
        run: java -cp build/libs/gitmc.jar io.github.nickid2018.gitmc.CheckMinecraft

      - name: Run output shell
        run: |
          chmod +x $GITHUB_WORKSPACE/output.sh
          $GITHUB_WORKSPACE/output.sh

      - name: Check out Write Branch
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.DESTINATION }}
          ref: ${{ env.branch_from }}
          ssh-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          path: write

      - name: Decompile Minecraft file
        if: ${{ env.fail != true }}
        run: java -cp build/libs/gitmc.jar org.benf.cfr.reader.Main --silent true --outputdir write --comments false remapped.jar

